name: ci

on:
  push:
    branches: 'main'
  schedule:
    - cron: '55 * * * *'

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      SCTO_AUTH: ${{ secrets.SCTO_AUTH }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - run: Rscript code/update_views.R
