all:
  view_sheet_name: Cases
  preferred_date_format: '%d-%b-%Y'
systems:
  - country: Botswana
    environment: production
    main_file_url: https://docs.google.com/spreadsheets/d/1IbIMR_lV1fU-6lFG_PWSyZqwtmf8OZD9JR-gl4CTr7o
    mirror_file_url: https://docs.google.com/spreadsheets/d/1XKhly7lRqieTk9J1yq1EV6DupN0IJdthF-hhjWdpBZY
  - country: Botswana
    environment: testing
    main_file_url: https://docs.google.com/spreadsheets/d/1yeyxR85D4sg8v6TegPEuaPqVTQUvjIN2_VAzR16zJWI
    mirror_file_url: https://docs.google.com/spreadsheets/d/1VkyJJPM2fl6cWaiJW8aZ742QFPk9P1dH9AV2dnjcii8
  - country: Westeros
    environment: production
    main_file_url: https://docs.google.com/spreadsheets/d/1_GLVf0l2-aYwLF_livRpcnkPSdzDOyIvRMmxvm02tM4
    mirror_file_url: https://docs.google.com/spreadsheets/d/1dqHj2MVK1QD-OnwgIj07fE3pqPVSRQDZ7153UVj737M
  - country: Westeros
    environment: testing
    main_file_url: https://docs.google.com/spreadsheets/d/1f_re5Rk1fA9IHlwMht7Xv5invAnZKSbEVSLWp0w3M8Q
    mirror_file_url: https://docs.google.com/spreadsheets/d/1zC2DdrnOhZqi3bm5p-h8eanS_02mxgX8r04hVhCND8M
  - country: SouthAfrica
    environment: production
    main_file_url: https://docs.google.com/spreadsheets/d/1Ro8ymy5EpkyuhaaOnoHMbxcDnNjAxsPSWEeARiVV7pg
    mirror_file_url: https://docs.google.com/spreadsheets/d/1Al6TYdz-A5HmXjTCDxM2SRmoPpVD1DdfJrXDCThTjkw
  - country: SouthAfrica
    environment: testing
    main_file_url: https://docs.google.com/spreadsheets/d/1OHeH4xh0IGCwX8G6iTfrbc9xEOGMCgHe218Yqcjcch4
    mirror_file_url: https://docs.google.com/spreadsheets/d/18y-2Nx5EP99ScPx7Gf-xidzylUxJbCPXe9SlIr-UbKc
