all:
  view_sheet_name: Cases
  preferred_date_format: '%d-%b-%Y'
systems:
  - country: Botswana
    environment: production
    main_file_url: https://docs.google.com/spreadsheets/d/1IbIMR_lV1fU-6lFG_PWSyZqwtmf8OZD9JR-gl4CTr7o
    mirror_file_url: https://docs.google.com/spreadsheets/d/1XKhly7lRqieTk9J1yq1EV6DupN0IJdthF-hhjWdpBZY
  - country: Botswana
    environment: testing
    main_file_url: https://docs.google.com/spreadsheets/d/1yeyxR85D4sg8v6TegPEuaPqVTQUvjIN2_VAzR16zJWI
    mirror_file_url: https://docs.google.com/spreadsheets/d/1VkyJJPM2fl6cWaiJW8aZ742QFPk9P1dH9AV2dnjcii8
  - country: Westeros
    environment: production
    main_file_url: https://docs.google.com/spreadsheets/d/1_GLVf0l2-aYwLF_livRpcnkPSdzDOyIvRMmxvm02tM4
    mirror_file_url: https://docs.google.com/spreadsheets/d/1dqHj2MVK1QD-OnwgIj07fE3pqPVSRQDZ7153UVj737M
  - country: Westeros
    environment: testing
    main_file_url: https://docs.google.com/spreadsheets/d/1f_re5Rk1fA9IHlwMht7Xv5invAnZKSbEVSLWp0w3M8Q
    mirror_file_url: https://docs.google.com/spreadsheets/d/1zC2DdrnOhZqi3bm5p-h8eanS_02mxgX8r04hVhCND8M
  - country: SouthAfrica
    environment: production
    main_file_url: https://docs.google.com/spreadsheets/d/1Ro8ymy5EpkyuhaaOnoHMbxcDnNjAxsPSWEeARiVV7pg
    mirror_file_url: https://docs.google.com/spreadsheets/d/1Al6TYdz-A5HmXjTCDxM2SRmoPpVD1DdfJrXDCThTjkw
  - country: SouthAfrica
    environment: testing
    main_file_url: https://docs.google.com/spreadsheets/d/1OHeH4xh0IGCwX8G6iTfrbc9xEOGMCgHe218Yqcjcch4
    mirror_file_url: https://docs.google.com/spreadsheets/d/18y-2Nx5EP99ScPx7Gf-xidzylUxJbCPXe9SlIr-UbKc
  - country: Namibia
    environment: production
    main_file_url: https://docs.google.com/spreadsheets/d/1TW1JHxJcpkDkcMmWQcinxDWBcgSEiQ71DesH53E8M1U
    mirror_file_url: https://docs.google.com/spreadsheets/d/1NBRqtL_EVCab2aTKdno52O6JBvHeBdc7k6wu4dUZVJ8
  - country: Namibia
    environment: testing
    main_file_url: https://docs.google.com/spreadsheets/d/13G808M06ckYxtj6x9CarQ_y36j_hOdAv5RlL2Qd1h5A
    mirror_file_url: https://docs.google.com/spreadsheets/d/1ne1sYUlOMWiALLvkSfoOAK2yTv7jbD8t0Sovf7oAR8A
  - country: Philippines
    environment: production
    main_file_url: https://docs.google.com/spreadsheets/d/1oD6LTtOM1rigC8sWnEqM4IeIYaZwPRRv3LPnIfNin9k
    mirror_file_url: https://docs.google.com/spreadsheets/d/1ZkNEjkrbe_H3aB-_Ph6cOxJsxtOWo0ftZ46mv4c6Kcc
 -  country: Philippines
    environment: testing
    main_file_url: https://docs.google.com/spreadsheets/d/1xErfoYZqq6Y6meMKD36lELqEFV9idRw9Mmau5HQb0ZI
    mirror_file_url: https://docs.google.com/spreadsheets/d/1gVHPHkt-2FMlMWIau7WMKtIK9NTb7ZHCpft8pTJ2noA

