name: ci

on:
  push:
    branches: 'main'
  #schedule:
  #  - cron: '30 1 * * *'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-views:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      SCTO_AUTH: ${{ secrets.SCTO_AUTH }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - run: Rscript code/populate_columns.R && Rscript code/update_views.R
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Youth Impact facilitator database
          to: jakejhughey@gmail.com
          from: Youth Impact Automation <youthimpactautomation@gmail.com>
          body: GitHub Actions detected a change to the facilitators dataset on SurveyCTO and has updated the Google Sheets accordingly!
