# production environment -> main branch
# testing environment -> testing branch
name: ci

on: workflow_dispatch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - run: Rscript code/update_views.R
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Youth Impact ${{ github.event.repository.name }} ${{ inputs.environment }}
          to: ${{ env.EMAIL_TO }}
          from: Youth Impact Automation <youthimpactautomation@gmail.com>
          body: |
            Hello there!

            GitHub Actions ran in the ${{ inputs.environment }} environment and gave the following message:

            ${{ env.MESSAGE }}

            ${{ env.RUN_URL }}
            ${{ env.FILE_URL }}

            Take care,
            Youth Impact Automation
