name: ci

on:
  repository_dispatch:
    types: [webhook]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      SCTO_AUTH: ${{ secrets.SCTO_AUTH }}
      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - run: Rscript code/update_views.R >> $GITHUB_ENV
      - name: Send email
        # if: ${{ env.MESSAGE != '0' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Youth Impact ${{ github.event.repository.name }}
          to: ${{ env.EMAIL_TO }}
          from: Youth Impact Automation <youthimpactautomation@gmail.com>
          body: |
            Hello there!

            GitHub Actions ran and gave the following message:

            ${{ env.MESSAGE }}

            ${{ env.RUN_URL }}
            ${{ env.FILE_URL }}

            Take care,
            Youth Impact Automation
