name: ci

on:
  push:
    branches: 'main'
  schedule:
    - cron: '30 * * * *'

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      SCTO_AUTH: ${{ secrets.SCTO_AUTH }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - run: Rscript code/populate_columns.R && Rscript code/update_views.R
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: jakejhughey@gmail.com, cryptochrome@gmail.com
          from: Youth Impact Automation <youthimpactautomation@gmail.com>
          body: Build job of ${{github.repository}} completed successfully!
